### ISSUE TITLE
Track memory usage and limit number of allocations

### ISSUE THREAD

**Issue by ioquatix** [socketry/async-rspec#1]
It would make sense to add.memory limits to specs, e.g. tracking memory usage and limits. It might be similar to the `timeout:` which can be used on a spec, something like `memory:`. Ideally, you can express exactly what you've said above - e.g. a constant upper bound for memory usage.

Additionally, it would be interesting to see if we can actually track, for example, the number of string allocations, and add that to a spec, similar to how IO is checked and all must be closed. It should be possible to say something like:

```
it "should receive chunks of data" do
    expect{
        chunk = body.read
    }.to limit_allocations(String => 1)
end
```

This would give me confidence that going forward we catch allocation issues. Otherwise, you might go to a lot of effort to implement such a path, but over time it may end up being damaged/broken by other changes. Without appropriate specs to catch such situations, we may loose your valuable contribution to memory usage.

https://github.com/socketry/falcon/issues/8

**Comment by ioquatix** [comment]
> I think it would be useful to release it as a separate gem, since it wouldn't be related to async (I can think of couple of other gems where I would like to add memory usage specs).

Fair enough. I actually agree. However, for the initial implementation, I'll probably do it in this gem.If it proves to be successful/useful we can extract it out/make a separate gem. I'm fine with that. I just want to try to avoid Cambrian explosion of gems for every feature :p

**Comment by ioquatix** [comment]
Here is the initial implementation:

https://github.com/socketry/async-rspec/blob/master/lib/async/rspec/memory.rb

Here is how to use it:

https://github.com/socketry/async-rspec/blob/master/spec/async/rspec/memory_spec.rb

I would like to make it support ranges `limit_allocations(String => 2..4)` and also perhaps minimum/maximum `limit_allocations(String => 2...)` (At least 2), `limit_allocations(String => 0...4)` (at most 4).

Also, I think it will break on JRuby but I'm not entirely sure yet.

**Comment by janko-m** [comment]
@ioquatix This looks great, thank you!! 🙏

Great, I'll then try to add specs for allocations when optimizing the socket wrappers in async-io/async-http/Falcon.
