### ISSUE TITLE
can async tasks persist between rspec tests?

### ISSUE THREAD

**Issue by emiltin** [socketry/async-rspec#17]
Hi,
Can async task persists between the rspec tests? E.g. a server task that connects to some site that should be tested and keeps the connection open between tests.

I would also need a way to start and stop the server in the RSpec :before_suite and :after_suite hooks.

**Comment by ioquatix** [comment]
No, and I believe you should avoid designing your tests like this.

**Comment by emiltin** [comment]
i generally agree. but in this case we're testing external equipment, where the connection sequence is slow. so we took the decision to keep the connection open between tests. in case, since it's external equipment, it's integration testing, not unit testing.

**Comment by ioquatix** [comment]
It would make sense to run two reactors then, one for the persistent stuff and one for the test stuff. To do this you need to use one extra thread.

**Comment by emiltin** [comment]
Yes maybe, although the tests have a lot of interaction with the server, to send messages to the equipment, wait for responses, etc. Some tests also requite the connection to be closed and reopened. That might introduce the thread-related coplexities that Async usually avoids.

The solution we've been using so far is to use a single reactor for the server and the tests, but call interrupt() on the reactor after the end of each test, and then run() at the start of each test. Interrupt is needed since the server task doesn't complete. This has worked quite well, bnut i wanted to take another look at async-rspec.

**Comment by ioquatix** [comment]
You can call stop on a sub-tree and it will be terminated without affecting the full reactor.

**Comment by emiltin** [comment]
yes that's useful, and probably better than waiting for all sub tasks, in a test setting. after the test task has run, it might be best to call stop on it to make all sub tasks are temrinated immediately.

the server would run in a separate task. i think i would still need to call interrupt() on the reactor (which is not a problem), since that server task doesn 't complete.

**Comment by emiltin** [comment]
closing asa the question is answered. thanks alot
