### ISSUE TITLE
reactor.with ?

### ISSUE THREAD

**Issue by matti** [socketry/async-rspec#6]
README mentions `reactor.with(output)` - it's not defined in reactor?

**Comment by ioquatix** [comment]
Sorry, it's a super old syntax. The original design of the reactor was to inject raw IO into a task, and it would be wrapped and given to the user. It worked like this:


```
s = TCPServer.new(...)

reactor.with(s) do |server|
    ... = server.accept
end
```

But after much experimentation I found it wasn't a good approach.

I'll amend the README.
